### ISSUE TITLE
Outline

### ISSUE THREAD

**Issue by BlackCA** [dankelley/black2018#2]
CA to write up a SFD of book outline, goals, feel, voice, etc.

**Comment by BlackCA** [comment]
SFD complete – to build on.

**Comment by dankelley** [comment]
A hint -- it's possible to put links into issues. There are some special shortcuts for things like referring to other issues. I don't know how to refer to the wiki without a full url. Anyhow ... my idea is that you could have written

"See https://github.com/dankelley/black2018/wiki/Topics "

in your comment, and then there would be a link to the change you had made.

**Comment by BlackCA** [comment]
OK, thanks.
